### PR TITLE
Update submissions Suryendu .md

### PR DESCRIPTION
**Pull request by SuryenduB**
# Cloud Resume API Challenge

### Step 2: Add Resume Data to the resume database

```zsh
aws dynamodb put-item \
    --table-name resume_json \
    --item file://resume.json

```

### Step 3: Retrieve the Item to verify resume data is correct

```zsh
aws dynamodb get-item \
    --table-name resume_json \
    --key '{"resumeid": {"N": "1"}}' \
    --projection-expression "resumedetails.basics","resumedetails.education","resumedetails.awards","resumedetails.certifications","resumedetails.skills","resumedetails.works"

```

### Step 6: Add Github Actions to deploy infrastructure.

### CODE REVIEW

**Comment by rishabkumar7** [comment]
Hi @SuryenduB thank you submitting. But I can't access the Resume API via the link shared. Could you make sure it is working.

**Review by SuryenduB — COMMENTED** [review]
Updated with new API linkl

**Comment by SuryenduB** [comment]
I have updated the PR.
I added **terraform destroy** workfkow later and had a test run.

This should work now.

**Comment by SuryenduB** [comment]
Merged

**Comment by SuryenduB** [comment]
Reopened

**Comment by rishabkumar7** [comment]
Awesome, it works!

**Review by rishabkumar7 — APPROVED** [review]

**Pull request merged**
