### PR TITLE
ADD: Emmanuel Nyame Cromwell submitted for AWS

### PR DESCRIPTION
**Pull request by P-Crommie**
This Pull Request introduces my submission of the Cloud Resume API challenge, a serverless API solution built with AWS Lambda and DynamoDB, and integrated with GitHub Actions for continuous deployment. The project demonstrates how to serve resume data in JSON format using a Lambda function, with automated deployment pipelines that ensure updates are seamlessly pushed to AWS.

**Services Used**
AWS Lambda: Executes the serverless function that fetches resume data from DynamoDB.
Amazon DynamoDB: Stores the resume data in a NoSQL database.
API Gateway: Exposes the Lambda function as a web API endpoint.
Amazon ECR: Hosts the Docker image for the Lambda function.
GitHub Actions: Automates the build, deployment, and testing processes.
Terraform: Manages the infrastructure as code for creating and managing AWS resources.

Screenshots/Architecture Diagram
cloudresume-api

### CODE REVIEW

**Review by rishabkumar7 — APPROVED** [review]
Thank you @P-Crommie for submitting, good job!

**Comment by rishabkumar7** [comment]
Hi @P-Crommie  congrats on winning the AWS Credits, could you share your preferred social media so that I can share the details. Thank you.

**Comment by P-Crommie** [comment]
Thank you @rishabkumar7. Sure, you can connect with me on X at _crommie_. Looking forward to the details! Thank you for the opportunity to learn and grow.

**Comment by rishabkumar7** [comment]
@P-Crommie is this correct - https://x.com/crommie

**Comment by P-Crommie** [comment]
It is "@_crommie_"

**Comment by rishabkumar7** [comment]
Can't seem to DM you, can you DM me instead.

**Pull request merged**
