### PR TITLE
Update submissions.md

### PR DESCRIPTION
**Pull request by jv199768**
https://github.com/jv199768/cloud-resume-api
https://6d7glxgbel2lb6nfht7p6zppsm0gikwg.lambda-url.us-east-1.on.aws/

### CODE REVIEW

**Comment by rishabkumar7** [comment]
Hey, thanks for your submission!
But I can't seem to fetch the resume via the lambda URL.

**Comment by jv199768** [comment]
I had to disable AWS_IAM Auth type in the Function URL configuration: 
https://aozgj6toda2a3tevccpbgz3spe0auadr.lambda-url.us-east-1.on.aws/

**Comment by rishabkumar7** [comment]
@jv199768 the API returns placeholder data, not your personal resume data. Typically the idea of the project is to serve your Resume as an API endpoint (JSON). But I would understand, if this is due to privacy reasons.
Screenshot 2024-05-25 at 3 39 59 PM

**Comment by jv199768** [comment]
Correct 👍

**Comment by rishabkumar7** [comment]
Sounds good.

**Review by rishabkumar7 — APPROVED** [review]

**Pull request merged**
