### PR TITLE
Submission

### PR DESCRIPTION
**Pull request by DevABM**
## Short description for your project
This is AWS Cloud Resume API Challenge where the resume is stored in json format in a dynamoDB table. An API trigger is used to run the lambda function to retrieve the data from the dynamoDB table. All AWS resources fo.r this project are provisioned by Terraform 

## Services used
Terraform, DynamoDB, Lambda and API gateway

## Screenshots/Architecture diagram
Screenshot 2024-07-28 at 7 07 54 PM

### CODE REVIEW

**Comment by DevABM** [comment]
Here is my submission to Cloud Resume API Challenge.

**Comment by rishabkumar7** [comment]
Hi @DevABM thank you for submission. But instead of creating a new `submission.md` file please update the existing one under `docs/submissions.md`. Add a new line to the respective project section, since your is AWS, add it in the table of AWS.

**Comment by DevABM** [comment]
Hi Rishab, i have added my submission to the AWS list as advised.
Thank You for this challenge.

**Comment by DevABM** [comment]
i have updated the url again

**Review by rishabkumar7 — APPROVED** [review]
LGTM!

**Pull request merged**
